

export {
  Globe,
  GlobeHemisphereWest,
  GlobeSimple,
  RocketLaunch,
  Rocket,
  Fire,
  Flame,
  Trophy,
  Sparkle,
  MagnifyingGlass,
  CheckCircle,
  Check,
  X,
  XCircle,
  ShieldCheck,
  ArrowRight,
  ArrowUpRight,
  CaretUp,
  CaretDown,
  Users,
  ChatCircle,
  ChatCircleText,
  TrendUp,
  MapPin,
  Calendar,
  CalendarBlank,
  Cpu,
  CreditCard,
  Coins,
  Cloud,
  HardDrives,
  SquaresFour,
  Suitcase,
  Sword,
  Handshake,
  Lightning,
  Eye,
  SlidersHorizontal,
  Plus,
  Funnel,
  Warning,
  WarningCircle,
  Clock,
  PencilSimple,
  Trash,
  Star,
  Export,
  ArrowSquareOut,
  GithubLogo,
  TwitterLogo,
  DiscordLogo,
  EnvelopeSimple,
  SignOut,
  User,
  List,
  Gift,
  DeviceMobile,
  Bell,
} from "@phosphor-icons/react/dist/ssr";

export {
 ArrowLeft, CaretLeft as ChevronLeft, CaretRight as ChevronRight,
 Warning as AlertTriangle, Archive, ArrowCounterClockwise as RotateCcw,
 SealCheck as BadgeCheck, CheckCircle as CheckCircle2, DownloadSimple as Download,
 Compass, Tray as Inbox, SquaresFour as LayoutDashboard, CircleNotch as Loader2,
 SignOut as LogOut, EnvelopeSimple as Mail, Megaphone, ChatCircle as MessageCircle,
 ChatCircleText as MessageSquare, Monitor, Moon, SidebarSimple as PanelLeftClose,
 SidebarSimple as PanelLeftOpen, Confetti as PartyPopper, Pause, PencilSimple as Pencil,
 Play, MagnifyingGlass as Search, PaperPlaneTilt as Send, Gear as Settings,
 Shield, ShieldWarning as ShieldAlert, Sparkle as Sparkles, Sun, Sword as Swords,
 Target, ThumbsUp, Trash as Trash2, TrendUp as TrendingUp,
} from "@phosphor-icons/react/dist/ssr";
export type { Icon as LucideIcon } from "@phosphor-icons/react";
