import Link from "next/link";
import type { ReactNode } from "react";
import type { ListItem } from "@/lib/platform";

export function PlatformPage({title,description,children}: {title:string;description?:string;children:ReactNode}) {
 return <div className="site-container space-y-8 py-8 sm:py-12"><header><p className="mb-3 text-xs font-mono uppercase tracking-widest text-muted-foreground">WeFounders / Community</p><h1 className="text-3xl sm:text-5xl tracking-tight">{title}</h1>{description&&<p className="mt-4 max-w-2xl text-muted-foreground">{description}</p>}</header>{children}</div>;
}
export function Panel({title,children}: {title?:string;children:ReactNode}) {return <section className="rounded-xl border border-border bg-card p-4 sm:p-6">{title&&<h2 className="mb-5 text-xl">{title}</h2>}{children}</section>;}
export function Field({label,name,type="text",value="",required=false,maxLength=2000}: {label:string;name:string;type?:string;value?:string|number;required?:boolean;maxLength?:number}) {return <label className="block text-sm font-medium">{label}{type==='textarea'?<textarea name={name} defaultValue={value} required={required} maxLength={maxLength} rows={4} className="mt-2 w-full rounded-lg border border-border bg-background p-3 font-normal"/>:<input name={name} type={type} defaultValue={value} required={required} maxLength={maxLength} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3 font-normal"/>}</label>;}
export function ItemList({items,empty="Nothing here yet.",cta="Explore launches",href="/discover"}: {items:ListItem[];empty?:string;cta?:string;href?:string}) {return items.length?<ul className="divide-y divide-border">{items.map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0 flex-1"><Link href={item.href} className="font-semibold hover:underline break-words">{item.title}</Link><p className="mt-1 text-sm text-muted-foreground break-words">{item.description}</p>{item.created_at&&<time className="text-xs text-muted-foreground" dateTime={item.created_at}>{new Date(item.created_at).toLocaleDateString('en-GB',{timeZone:'UTC'})}</time>}</div>{item.status&&<span className="rounded-full border border-border px-3 py-1 text-xs">{item.status.replace(/_/g,' ')}</span>}{item.value!==undefined&&<span className="font-mono tabular-nums">{item.value}</span>}</li>)}</ul>:<div className="py-6"><p className="text-muted-foreground">{empty}</p><Link className="mt-4 inline-block font-medium underline underline-offset-4" href={href}>{cta}</Link></div>;}
export function MemberNav() {return <nav aria-label="Account" className="flex flex-wrap gap-2">{[['/dashboard','Overview'],['/dashboard/founder','Founder'],['/dashboard/tester','Tester'],['/notifications','Notifications'],['/following','Following'],['/saved','Saved'],['/karma','Karma'],['/settings','Settings']].map(([href,label])=><Link key={href} href={href} className="rounded-lg border border-border px-3 py-2 text-sm hover:bg-secondary">{label}</Link>)}</nav>;}
