import { requireMember } from "@/lib/platform";
import { saveProfile } from "@/actions/community";
import { ActionForm } from "@/components/platform/action-form";
import { PlatformPage, Panel, Field, MemberNav } from "@/components/platform/ui";
import Link from "next/link";
export const dynamic="force-dynamic";
export const metadata={title:"Profile settings",robots:{index:false,follow:false}};
export default async function Settings() {
 const user=await requireMember();
 return <PlatformPage title="Make it yours" description="Your public profile and notification preferences."><MemberNav/><Panel title="Profile"><ActionForm action={saveProfile} label="Save profile"><div className="grid gap-4 sm:grid-cols-2"><Field name="name" label="Display name" value={user.full_name} required maxLength={80}/><Field name="location" label="Location" value={user.location} maxLength={120}/><Field name="website" label="Portfolio / website" type="url" value={user.website_url??''}/><Field name="availability" label="Availability" value={user.availability}/><Field name="github" label="GitHub username" value={user.github_handle??''}/><Field name="twitter" label="X username" value={user.twitter_handle??''}/></div><Field name="bio" type="textarea" label="About you" value={user.bio??''}/><Field name="skills" label="Skills, separated by commas" value={user.skills.join(', ')}/><Field name="interests" label="Interests, separated by commas" value={user.interests.join(', ')}/><fieldset><legend className="mb-3 font-medium">Your roles</legend><div className="flex flex-wrap gap-4">{['founder','builder','tester','designer','developer','marketer','investor','advisor'].map(role=><label key={role} className="flex items-center gap-2 capitalize"><input type="checkbox" name="roles" value={role} defaultChecked={user.member_roles.includes(role)}/>{role}</label>)}</div></fieldset><fieldset className="space-y-3"><legend className="mb-3 font-medium">Email preferences</legend><label className="flex gap-3"><input type="checkbox" name="emailNotifications" defaultChecked={user.email_notifications}/>Product updates and account notifications</label><label className="flex gap-3"><input type="checkbox" name="weeklyDigest" defaultChecked={user.weekly_digest}/>Weekly community digest</label></fieldset></ActionForm></Panel><p><Link href={`/profile/${user.username}`} className="underline">View public profile</Link></p><Panel title="Your referral link"><p className="break-all font-mono text-sm">https://wefounders.dev/sign-up?ref={user.referral_code}</p><p className="mt-3 text-sm text-muted-foreground">Referral reputation is earned only after the new member completes an accepted quest. Self-referrals and repeat credit are blocked.</p></Panel></PlatformPage>;
}
