import Link from "next/link";
import { notFound } from "next/navigation";
import { verifyAdmin } from "@/lib/auth/admin";
import { sql } from "@/lib/db/neon";
import { manageUser,moderate,savePlatformSettings,saveTaxonomy,requestRefund } from "@/app/admin/platform-actions";
import { reviewSubmission } from "@/actions/community";
import { ActionForm } from "@/components/platform/action-form";
import { Panel,Field } from "@/components/platform/ui";

const sections=['users','reports','payments','analytics','settings','audit-log','quest-review','collab-review'];
export async function AdminPlatformTools({section,q=''}:{section:string;q?:string}){
 await verifyAdmin();if(!sections.includes(section))notFound();
 const search=q.slice(0,100);const title=section.replace(/-/g,' ');
 let content;
 if(section==='users'){
  const users=await sql`select id,full_name,username,email,role,suspended_at,verified_at,created_at,(select count(*)::int from startups where founder_id=p.id) as launches,(select count(*)::int from quest_submissions where tester_id=p.id) as reports from profiles p where full_name ilike ${'%'+search+'%'} or username ilike ${'%'+search+'%'} or email ilike ${'%'+search+'%'} order by created_at desc limit 100` as {id:string;full_name:string;username:string;email:string;role:string;suspended_at:string|null;verified_at:string|null;created_at:string;launches:number;reports:number}[];
  content=<><form className="mb-6 flex gap-3"><input name="q" aria-label="Search users" defaultValue={search} className="min-w-0 flex-1 rounded-lg border bg-background p-3"/><button className="ink-button px-4">Search</button></form><div className="space-y-5">{users.map(u=><Panel key={u.id} title={u.full_name||u.username}><Link href={`/profile/${u.username}`} className="text-sm underline">View public profile</Link><p className="mt-3 break-all text-sm text-muted-foreground">{u.email} · {u.role} · {u.suspended_at?'Suspended':'Active'} · {u.verified_at?'Verified':'Unverified'}</p><p className="my-3 text-xs">{u.launches} launches · {u.reports} testing reports</p><ActionForm action={manageUser} label="Apply user change" confirm="Apply this account or permission change? It will be recorded in the audit log."><input type="hidden" name="id" value={u.id}/><div className="flex flex-wrap gap-3"><select name="operation" aria-label="User operation" className="rounded-lg border bg-background p-3"><option value="role">Change role</option><option value="suspend">Suspend</option><option value="unsuspend">Unsuspend</option><option value="verify">Verify member</option><option value="unverify">Remove verification</option></select><select name="role" aria-label="New role" defaultValue={u.role} className="rounded-lg border bg-background p-3">{['user','founder','moderator','admin'].map(r=><option key={r}>{r}</option>)}</select></div></ActionForm></Panel>)}</div></>;
 }else if(section==='reports'){
  const rows=await sql`select r.*,p.username from reports r join profiles p on p.id=r.reporter_id order by (status='open') desc,created_at desc limit 100` as {id:string;target_type:string;target_id:string;reason:string;description:string;status:string;username:string}[];
  content=rows.length?<div className="space-y-5">{rows.map(r=><Panel key={r.id} title={`${r.target_type} / ${r.reason}`}><p className="text-sm">Record: {r.target_id}</p><p className="my-3 whitespace-pre-wrap">{r.description}</p><p className="mb-4 text-sm text-muted-foreground">Reported by {r.username} · {r.status}</p>{r.status==='open'&&<ActionForm action={moderate} label="Resolve report"><input type="hidden" name="id" value={r.id}/><input type="hidden" name="kind" value="report"/><select name="operation" aria-label="Resolution" className="rounded-lg border bg-background p-3"><option value="resolve">Resolve</option><option value="dismiss">Dismiss</option></select><Field name="reason" label="Resolution notes" required/></ActionForm>}{r.target_type==='profile'?<ActionForm action={manageUser} label="Suspend reported user" confirm="Suspend this account? The change is audited."><input type="hidden" name="id" value={r.target_id}/><input type="hidden" name="operation" value="suspend"/></ActionForm>:<ActionForm action={moderate} label="Moderate reported content" confirm="Apply this moderation action?"><input type="hidden" name="id" value={r.target_id}/><input type="hidden" name="kind" value={r.target_type}/><select name="operation" aria-label="Moderation action" className="rounded-lg border bg-background p-3">{(r.target_type==='comment'?['delete']:r.target_type==='quest'?['reject','pause','close']:['reject','archive']).map(op=><option key={op}>{op}</option>)}</select><Field name="reason" label="Moderation reason" required/></ActionForm>}</Panel>)}</div>:<Panel><p>No reports. Moderation reports will appear here as members flag content.</p></Panel>;
 }else if(section==='payments'){
  const rows=await sql`select p.id,p.reference_id,p.amount_npr,p.provider,p.status,p.created_at,p.refund_requested_at,p.refund_note,s.name,u.full_name from promotions p join startups s on s.id=p.startup_id join profiles u on u.id=p.founder_id order by p.created_at desc limit 100` as {id:string;reference_id:string;amount_npr:number;provider:string;status:string;created_at:string;refund_requested_at:string|null;refund_note:string|null;name:string;full_name:string}[];
  content=<><p className="mb-5 text-sm text-muted-foreground">Ledger states change only after provider verification. Refund review records the request; execute refunds in the provider dashboard. No credentials or card data are stored here.</p>{rows.length?rows.map(p=><Panel key={p.id} title={p.name}><p className="break-all text-sm">{p.reference_id}</p><p className="mt-3">{p.full_name} · NPR {p.amount_npr} · {p.provider} · {p.status}</p><p className="my-3 text-xs">{new Date(p.created_at).toLocaleString('en-GB')}</p>{p.refund_requested_at?<p>Refund review requested: {p.refund_note}</p>:p.status==='completed'&&<ActionForm action={requestRefund} label="Request refund review"><input type="hidden" name="id" value={p.id}/><Field name="reason" label="Refund reason" required/></ActionForm>}</Panel>):<Panel><p>No payment transactions recorded.</p></Panel>}</>;
 }else if(section==='audit-log'){
  const rows=await sql`select a.id,a.action,a.target_type,a.target_id,a.created_at,a.details,p.username from audit_log a left join profiles p on p.id=a.actor_id order by a.created_at desc limit 200` as {id:string;action:string;target_type:string;target_id:string;created_at:string;details:Record<string,unknown>;username:string|null}[];
  content=<Panel><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Recent sensitive platform changes</caption><thead><tr>{['Time','Actor','Action','Target','Details'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="whitespace-nowrap p-3">{new Date(r.created_at).toLocaleString('en-GB')}</td><td className="p-3">{r.username??'System / migration'}</td><td className="p-3">{r.action}</td><td className="p-3">{r.target_type}<span className="block text-xs">{r.target_id}</span></td><td className="max-w-sm break-words p-3 text-xs">{JSON.stringify(r.details)}</td></tr>)}</tbody></table></div></Panel>;
 }else if(section==='analytics'){
  const stats=(await sql`select (select count(*) from profiles) as users,(select count(distinct user_id) from upvotes where created_at>now()-interval '7 days') as active_voters,(select count(*) from startups where status='approved' and archived_at is null) as launches,(select count(*) from quest_members) as participants,(select count(*) from quest_submissions where status='accepted') as accepted,(select coalesce(sum(amount_npr),0) from promotions where status='completed') as revenue,(select count(*) from promotions where status='completed') as promotions,(select count(distinct user_id) from upvotes where created_at>now()-interval '7 days' and user_id in(select user_id from upvotes where created_at between now()-interval '14 days' and now()-interval '7 days')) as returning_voters`)[0];
  const daily=await sql`select created_at::date::text as day,count(*)::int as users from profiles group by created_at::date order by day desc limit 30` as {day:string;users:number}[];
  content=<><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Object.entries(stats).map(([key,value])=><Panel key={key}><p className="text-sm text-muted-foreground capitalize">{key.replace(/_/g,' ')}</p><p className="mt-3 text-3xl font-mono">{String(value)}</p></Panel>)}</div><Panel title="New members by day">{daily.length?<ul className="space-y-3">{daily.map(d=><li key={d.day} className="flex justify-between"><span>{d.day}</span><span>{d.users}</span></li>)}</ul>:<p>No membership history yet.</p>}</Panel><p className="text-sm text-muted-foreground">Active and returning metrics use persisted upvote activity. Returning voters participated in both of the last two weeks. Revenue is completed payments in NPR.</p></>;
 }else if(section==='settings'){
  const rows=await sql`select key,value from platform_settings order by key` as {key:string;value:unknown}[];
  content=<><Panel title="Platform configuration"><p className="mb-5 text-sm text-muted-foreground">Promotion plans are unavailable until you configure actual prices and terms. Each change is validated and audited.</p><ActionForm action={savePlatformSettings} label="Save configuration" confirm="Publish these platform settings?"><label>Setting<select name="key" className="ml-3 rounded-lg border bg-background p-3">{['promotion_plans','feature_flags','notification_templates','moderation_rules'].map(key=><option key={key}>{key}</option>)}</select></label><Field name="value" label="JSON value" type="textarea" value="[]" maxLength={20000}/></ActionForm><details className="mt-5 text-sm"><summary>Promotion plan format</summary><pre className="mt-3 whitespace-pre-wrap break-words">{'[{"tier":"featured_48h","label":"Your plan name","durationHours":48,"priceNpr":YOUR_REAL_PRICE,"blurb":"Your terms","perks":["Your placement terms"]}]'}</pre></details><ul className="mt-6 space-y-3">{rows.map(r=><li key={r.key}><strong>{r.key}</strong><pre className="mt-2 whitespace-pre-wrap break-all text-xs">{JSON.stringify(r.value,null,2)}</pre></li>)}</ul></Panel><Panel title="Categories and tags"><ActionForm action={saveTaxonomy} label="Save taxonomy"><Field name="name" label="Name" required/><select name="category" aria-label="Taxonomy category" className="rounded-lg border bg-background p-3">{['industry','stack','payment','telecom'].map(c=><option key={c}>{c}</option>)}</select></ActionForm></Panel><Panel title="Services"><ul className="space-y-3">{[['Database',!!process.env.DATABASE_URL],['Authentication',!!process.env.CLERK_SECRET_KEY],['Email delivery',!!process.env.RESEND_API_KEY],['Scheduled delivery',!!process.env.CRON_SECRET]].map(([label,ready])=><li key={String(label)} className="flex justify-between">{label}<span>{ready?'Configured':'Not configured'}</span></li>)}</ul></Panel></>;
 }else{
  const quests=section==='quest-review';const rows=quests?await sql`select id,title,task_instructions as description,approval_status as status from testing_quests where approval_status='pending' order by created_at`:await sql`select id,title,description,approval_status as status from collab_posts where approval_status='pending' order by created_at`;
  content=<><div className="space-y-4">{rows.length?rows.map(r=><Panel key={String(r.id)} title={String(r.title)}><p className="mb-4 whitespace-pre-wrap">{String(r.description)}</p><ActionForm action={moderate} label="Apply moderation"><input type="hidden" name="id" value={String(r.id)}/><input type="hidden" name="kind" value={quests?'quest':'collab'}/><select aria-label="Moderation decision" name="operation" className="rounded-lg border bg-background p-3"><option value="approve">Approve</option><option value="reject">Reject</option></select><Field name="reason" label="Moderation notes"/></ActionForm></Panel>):<Panel><p>No pending submissions.</p></Panel>}</div>{quests&&<QuestReports/>}</>;
 }
 return <div className="admin-platform space-y-6"><header><h1 className="text-2xl capitalize sm:text-3xl">{title}</h1><p className="mt-3 text-sm text-muted-foreground">Live records. Changes require server authorization and are recorded in the audit log.</p></header>{content}</div>;
}

async function QuestReports(){const rows=await sql`select r.id,r.feedback_text,r.tester_name,r.status,q.title from quest_submissions r join testing_quests q on q.id=r.quest_id where r.status='pending' order by r.created_at desc limit 100`;return <Panel title="Pending tester reviews">{rows.length?rows.map(r=><article key={String(r.id)} className="border-b py-5"><h3>{String(r.title)} · {String(r.tester_name)}</h3><p className="my-4 whitespace-pre-wrap">{String(r.feedback_text)}</p><ActionForm action={reviewSubmission} label="Review report"><input type="hidden" name="id" value={String(r.id)}/><select name="decision" className="rounded-lg border bg-background p-3"><option value="approved">Approve and credit Karma</option><option value="needs_changes">Request changes</option><option value="rejected">Reject</option></select><Field name="feedback" label="Review feedback" required/></ActionForm></article>):<p>No reports awaiting review.</p>}</Panel>;}
