import { readFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { neon } from "@neondatabase/serverless";
import dotenv from "dotenv";

// Load environment variables
dotenv.config({ path: ".env.local" });
dotenv.config();

const DATABASE_URL = process.env.DATABASE_URL?.trim();

if (!DATABASE_URL) {
  console.error("❌ Set DATABASE_URL in .env.local (Neon pooled connection string)");
  process.exit(1);
}

const sql = neon(DATABASE_URL);

const founderSchema = z.object({
  fullName: z.string().min(1),
  username: z.string().min(1),
  email: z.string().email(),
});

const launchSchema = z.object({
  slug: z.string().min(1),
  name: z.string().min(1),
  tagline: z.string().min(1),
  problem: z.string().min(1),
  solution: z.string().min(1),
  category: z.string().min(1),
  tags: z.array(z.string()),
  websiteUrl: z.string().url(),
  logoUrl: z.string().url(),
  screenshots: z.array(z.string().url()),
  founder: founderSchema,
  launchDate: z.string().datetime().optional(),
});

const batchSchema = z.array(launchSchema);

// Checks if a URL returns HTTP 200
async function verifyUrl(url: string): Promise<boolean> {
  try {
    const res = await fetch(url, { method: "HEAD" });
    return res.ok;
  } catch {
    return false;
  }
}

function isPlaceholder(url: string): boolean {
  const placeholders = ["via.placeholder.com", "dummyimage.com", "placehold.co"];
  return placeholders.some((ph) => url.includes(ph));
}

async function main() {
  const fileArg = process.argv.find((arg) => arg.startsWith("--file="));
  if (!fileArg) {
    console.error("❌ Provide a JSON file using --file=filename.json");
    process.exit(1);
  }

  const filePath = path.resolve(process.cwd(), fileArg.split("=")[1]);
  console.log(`Loading seed data from ${filePath} ...`);

  let fileContent: string;
  try {
    fileContent = await readFile(filePath, "utf8");
  } catch {
    console.error(`❌ Could not read file: ${filePath}`);
    process.exit(1);
  }

  let jsonData: unknown;
  try {
    jsonData = JSON.parse(fileContent);
  } catch {
    console.error("❌ File is not valid JSON.");
    process.exit(1);
  }

  const parseResult = batchSchema.safeParse(jsonData);
  if (!parseResult.success) {
    console.error("❌ JSON does not match the strict schema:");
    console.error(parseResult.error.format());
    process.exit(1);
  }

  const entries = parseResult.data;
  let passed = 0;
  let failed = 0;

  for (const entry of entries) {
    console.log(`\nProcessing startup: ${entry.name}`);

    const isUrlValid = await verifyUrl(entry.websiteUrl);
    if (!isUrlValid) {
      console.error(`  ❌ websiteUrl ${entry.websiteUrl} did not return HTTP 200`);
      failed++;
      continue;
    }

    const urlsToCheck = [entry.logoUrl, ...entry.screenshots];
    if (urlsToCheck.some(isPlaceholder)) {
      console.error(`  ❌ Rejected placeholder media found in URLs`);
      failed++;
      continue;
    }

    const launchDate = entry.launchDate ?? new Date().toISOString();

    // 1. Ensure the founder exists — profile ids are generated by Postgres, and
    //    `clerk_user_id` is a placeholder until that person signs in for real.
    const founders = (await sql`
      select id from profiles where email = ${entry.founder.email} limit 1
    `) as { id: string }[];

    let founderId = founders[0]?.id;

    if (!founderId) {
      const created = (await sql`
        insert into profiles (id, clerk_user_id, email, full_name, username, role, is_phone_verified, karma_score)
        values (
          gen_random_uuid(),
          ${`seed-${crypto.randomUUID()}`},
          ${entry.founder.email},
          ${entry.founder.fullName},
          ${entry.founder.username},
          'founder',
          false,
          0
        )
        returning id
      `) as { id: string }[];
      founderId = created[0]?.id;
      if (!founderId) {
        console.error(`  ❌ Failed to create founder (username may already be taken)`);
        failed++;
        continue;
      }
    }

    // 2. Insert the startup.
    const description = `**Problem:**\n${entry.problem}\n\n**Solution:**\n${entry.solution}`;
    const startups = (await sql`
      insert into startups (
        founder_id, slug, name, tagline, description,
        website_url, logo_url, stage, target_market, status, launch_date
      )
      values (
        ${founderId}::uuid,
        ${entry.slug},
        ${entry.name},
        ${entry.tagline},
        ${description},
        ${entry.websiteUrl},
        ${entry.logoUrl},
        'launched',
        'nepal_domestic',
        'approved',
        ${launchDate}
      )
      returning id
    `) as { id: string }[];

    const startupId = startups[0]?.id;
    if (!startupId) {
      console.error(`  ❌ Failed to insert startup (slug may already be taken)`);
      failed++;
      continue;
    }

    // 3. Screenshots.
    if (entry.screenshots.length > 0) {
      await sql`
        insert into startup_media (startup_id, media_url, media_type, display_order)
        select ${startupId}::uuid, media.media_url, 'image', media.display_order
        from jsonb_to_recordset(${JSON.stringify(
          entry.screenshots.map((url, index) => ({ media_url: url, display_order: index }))
        )}::jsonb) as media(media_url text, display_order integer)
      `;
    }

    // 4. Tags, including the founding-batch badge.
    const combinedTags = Array.from(new Set([...entry.tags, "founding-batch"]));

    await sql`
      insert into tags (slug, name, category)
      select incoming.slug, incoming.name, 'industry'
      from jsonb_to_recordset(${JSON.stringify(
        combinedTags.map((slug) => ({ slug, name: slug === "founding-batch" ? "Founding Batch" : slug }))
      )}::jsonb) as incoming(slug text, name text)
      on conflict (slug) do nothing
    `;

    await sql`
      insert into startup_tags (startup_id, tag_id)
      select ${startupId}::uuid, tags.id
      from tags
      where tags.slug = any(${combinedTags}::text[])
      on conflict do nothing
    `;

    console.log(`  ✅ Successfully seeded startup (${startupId})`);
    passed++;
  }

  console.log(`\nSeed Complete. ✅ Passed: ${passed} | ❌ Failed: ${failed}`);
}

main().catch((error) => {
  console.error("Unhandled error:", error);
  process.exit(1);
});